server:
  port: 9891

spring:
  profiles:
    active: dev
  # 应用配置
  application:
    name: dy-test

  # 动态线程池配置
  dynamic:
    thread-pool:
      server-addr: http://localhost:6691
      namespace: apollo
      item-id: dy-test
      username: admin
      password: 123456
      enable: true

app:
  id: configex-apollo
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
  autoUpdateInjectedSpringProperties:
    false
logging:
  level:
    com: info