server:
  port: 8888


nacos:
  config:
    server-addr: 127.0.0.1:8848
    type: yaml
    data-ids: config_group, dynamic-tp-demo-dev.yml
    auto-refresh: true
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log-enable: true


#logging:
#  level:
#    root: DEBUG

#management:
#  metrics:
#    tags:
#      application: ${spring.application.name}
#  endpoints:
#    web:
#      exposure:
#        include: '*'
